# Generated by Django 4.1.3 on 2023-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_remove_whiteboard_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboardinformation',
            name='undo',
            field=models.BooleanField(default=None),
        ),
    ]
